"""
API Compliance Fixer — FastAPI Backend v7
Trial flow:
  - Upload → redacted preview (2 rules shown, rest locked)
  - User chooses: paste existing token OR submit request form
  - Request form → Google Forms (no email sent, team reaches out manually)
  - Admin generates per-user tokens at /admin/generate?key=ADMIN_KEY
  - Token redemption → full changelog + one-time download token
"""
from __future__ import annotations

import io
import json
import os
import secrets
import zipfile
from datetime import datetime, timezone
from pathlib import Path

import httpx
from fastapi import FastAPI, File, Form, HTTPException, Request, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse, StreamingResponse
from fastapi.staticfiles import StaticFiles

from frameworks import FRAMEWORK_META, FRAMEWORK_RULES
from transform import detect_format, preview, transform

# ═══════════════════════════════════════════════════════════════════════════════
# CONFIG
# ═══════════════════════════════════════════════════════════════════════════════

BASE_URL         = os.getenv("BASE_URL", "http://localhost:8000")
MAX_UPLOAD_BYTES = 10 * 1024 * 1024
VALID_FRAMEWORKS = set(FRAMEWORK_META.keys())

# Admin key — protects /admin/* endpoints
# Set a strong random string in Railway env vars
ADMIN_KEY = os.getenv("ADMIN_KEY", "")

# Google Forms
GFORM_URL        = os.getenv("GFORM_URL", "")
GFORM_NAME       = os.getenv("GFORM_NAME",       "entry.000000001")
GFORM_EMAIL      = os.getenv("GFORM_EMAIL",      "entry.000000002")
GFORM_COMPANY    = os.getenv("GFORM_COMPANY",    "entry.000000003")
GFORM_ROLE       = os.getenv("GFORM_ROLE",       "entry.000000004")
GFORM_HOW_HEARD  = os.getenv("GFORM_HOW_HEARD",  "entry.000000005")
GFORM_USE_CASE   = os.getenv("GFORM_USE_CASE",   "entry.000000006")
GFORM_COLLECTION = os.getenv("GFORM_COLLECTION", "entry.000000007")
GFORM_FRAMEWORKS = os.getenv("GFORM_FRAMEWORKS", "entry.000000008")
GFORM_CHANGES    = os.getenv("GFORM_CHANGES",    "entry.000000009")
GFORM_FORMAT     = os.getenv("GFORM_FORMAT",     "entry.000000010")
GFORM_TIMESTAMP  = os.getenv("GFORM_TIMESTAMP",  "entry.000000011")

# ═══════════════════════════════════════════════════════════════════════════════
# IN-MEMORY STORES
# ═══════════════════════════════════════════════════════════════════════════════

# upload_token → { raw, filename, frameworks, format, changelog }
pending_uploads: dict[str, dict] = {}

# access_token → { label, email, created_at, use_count }
# Generated by admin. Free-standing — not tied to a specific upload.
# Redeemable multiple times (upload sessions are independent).
issued_tokens: dict[str, dict] = {}

# download_token → { raw, filename, frameworks, format }
# Single-use. Issued on each successful redemption.
download_tokens: dict[str, dict] = {}

# ═══════════════════════════════════════════════════════════════════════════════
# APP
# ═══════════════════════════════════════════════════════════════════════════════

app = FastAPI(title="API Compliance Fixer — Trial", version="7.0.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], allow_methods=["*"], allow_headers=["*"],
)

static_dir = Path(__file__).parent / "static"
app.mount("/static", StaticFiles(directory=str(static_dir)), name="static")


# ═══════════════════════════════════════════════════════════════════════════════
# HELPERS
# ═══════════════════════════════════════════════════════════════════════════════

def _require_admin(key: str) -> None:
    """Raise 403 if the provided key doesn't match ADMIN_KEY."""
    if not ADMIN_KEY:
        raise HTTPException(503, "Admin key not configured — set ADMIN_KEY env var.")
    if key != ADMIN_KEY:
        raise HTTPException(403, "Invalid admin key.")


def _parse_frameworks(s: str) -> list[str]:
    ids = [f.strip().upper() for f in s.split(",") if f.strip()]
    bad = [f for f in ids if f not in VALID_FRAMEWORKS]
    if bad:
        raise HTTPException(400, f"Unknown frameworks: {', '.join(bad)}.")
    if not ids:
        raise HTTPException(400, "At least one framework must be selected.")
    return list(dict.fromkeys(ids))


def _try_yaml(raw: bytes) -> dict:
    try:
        import yaml
        return yaml.safe_load(raw)
    except Exception:
        raise HTTPException(422, "File is not valid JSON or YAML.")


def _parse_file(raw: bytes, filename: str) -> dict:
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        if filename.endswith((".yaml", ".yml")):
            return _try_yaml(raw)
        raise HTTPException(422, "Invalid JSON. Use .yaml/.yml for YAML files.")


def _col_name(entry: dict) -> str:
    try:
        d = json.loads(entry["raw"])
        key = "name" if entry["format"] == "postman" else "title"
        return d.get("info", {}).get(key, "API File")
    except Exception:
        return "API File"


def _fw_label(entry: dict) -> str:
    return " + ".join(
        FRAMEWORK_META[f]["name"] for f in entry["frameworks"] if f in FRAMEWORK_META
    )


def _redact_changelog(changelog: dict, preview_rules: int = 2) -> dict:
    """Return a changelog with only the first N rules visible."""
    rules    = changelog.get("changes_by_rule", [])
    hidden_n = max(0, len(rules) - preview_rules)
    return {
        **changelog,
        "changes_by_rule": rules[:preview_rules],
        "hidden_rules":    hidden_n,
        "redacted":        True,
    }


# ═══════════════════════════════════════════════════════════════════════════════
# GOOGLE FORMS
# ═══════════════════════════════════════════════════════════════════════════════

async def _submit_to_gform(data: dict) -> None:
    """Fire-and-forget POST to Google Form. Never raises."""
    if not GFORM_URL:
        print(f"[GFORM] Not configured. Data: {json.dumps(data)}")
        return
    payload = {
        GFORM_NAME:       data.get("name", ""),
        GFORM_EMAIL:      data.get("email", ""),
        GFORM_COMPANY:    data.get("company", ""),
        GFORM_ROLE:       data.get("role", ""),
        GFORM_HOW_HEARD:  data.get("how_heard", ""),
        GFORM_USE_CASE:   data.get("use_case", ""),
        GFORM_COLLECTION: data.get("collection_name", ""),
        GFORM_FRAMEWORKS: data.get("frameworks", ""),
        GFORM_CHANGES:    str(data.get("total_changes", "")),
        GFORM_FORMAT:     data.get("format", ""),
        GFORM_TIMESTAMP:  data.get("timestamp", ""),
    }
    try:
        async with httpx.AsyncClient(follow_redirects=True) as client:
            await client.post(
                GFORM_URL, data=payload,
                headers={"Content-Type": "application/x-www-form-urlencoded"},
                timeout=8,
            )
    except Exception as exc:
        print(f"[GFORM] Error: {exc}")


# ═══════════════════════════════════════════════════════════════════════════════
# ROUTES — PUBLIC
# ═══════════════════════════════════════════════════════════════════════════════

@app.get("/", response_class=HTMLResponse)
async def root():
    return HTMLResponse((static_dir / "index.html").read_text(encoding="utf-8"))


@app.get("/api/frameworks")
async def list_frameworks():
    return [
        {
            **meta,
            "rule_count": len(FRAMEWORK_RULES.get(fid, [])),
            "rules": [
                {"id": r.id, "title": r.title, "severity": r.severity, "reference": r.reference}
                for r in FRAMEWORK_RULES.get(fid, [])
            ],
        }
        for fid, meta in FRAMEWORK_META.items()
    ]


@app.get("/api/health")
async def health():
    return {
        "status":           "ok",
        "version":          "7.0.0",
        "mode":             "token-gated trial",
        "admin_configured": bool(ADMIN_KEY),
        "gform_configured": bool(GFORM_URL),
        "tokens_issued":    len(issued_tokens),
        "frameworks":       list(FRAMEWORK_META.keys()),
    }


# ═══════════════════════════════════════════════════════════════════════════════
# ROUTES — UPLOAD
# ═══════════════════════════════════════════════════════════════════════════════

@app.post("/api/upload")
async def upload(file: UploadFile = File(...), frameworks: str = Form(...)):
    filename = file.filename or ""
    if not filename.endswith((".json", ".yaml", ".yml")):
        raise HTTPException(400, "Only .json, .yaml, or .yml files are accepted.")
    raw = await file.read()
    if len(raw) > MAX_UPLOAD_BYTES:
        raise HTTPException(413, "File exceeds 10 MB limit.")
    fw_ids  = _parse_frameworks(frameworks)
    parsed  = _parse_file(raw, filename)
    try:
        fmt = detect_format(parsed)
    except ValueError as exc:
        raise HTTPException(422, str(exc)) from exc
    full_changelog = preview(parsed, fw_ids)
    token = secrets.token_urlsafe(32)
    pending_uploads[token] = {
        "raw": raw, "filename": filename,
        "frameworks": fw_ids, "format": fmt,
        "changelog": full_changelog,
    }
    return {
        "upload_token":      token,
        "format":            fmt,
        "changelog_preview": _redact_changelog(full_changelog, preview_rules=2),
    }


# ═══════════════════════════════════════════════════════════════════════════════
# ROUTES — REQUEST ACCESS (form → Google Sheet, no token issued)
# ═══════════════════════════════════════════════════════════════════════════════

@app.post("/api/request-access")
async def request_access(
    upload_token: str = Form(...),
    name:         str = Form(...),
    email:        str = Form(...),
    company:      str = Form(""),
    role:         str = Form(""),
    how_heard:    str = Form(""),
    use_case:     str = Form(""),
):
    """
    Collect user details and log to Google Forms.
    No token is issued here — the team reviews and sends one manually.
    """
    entry = pending_uploads.get(upload_token)
    if not entry:
        raise HTTPException(404, "Upload not found or expired. Please re-upload your file.")

    name  = name.strip()
    email = email.strip().lower()
    if not name:
        raise HTTPException(400, "Name is required.")
    if not email or "@" not in email:
        raise HTTPException(400, "A valid email address is required.")

    changelog = entry.get("changelog", {})

    await _submit_to_gform({
        "timestamp":       datetime.now(timezone.utc).isoformat(),
        "name":            name,
        "email":           email,
        "company":         company.strip(),
        "role":            role.strip(),
        "how_heard":       how_heard,
        "use_case":        use_case,
        "collection_name": _col_name(entry),
        "frameworks":      ", ".join(entry["frameworks"]),
        "total_changes":   changelog.get("total_changes", 0),
        "format":          entry.get("format", ""),
    })

    return {
        "ok":      True,
        "message": "Request received. Our team will review and send your access token shortly.",
    }


# ═══════════════════════════════════════════════════════════════════════════════
# ROUTES — REDEEM TOKEN
# ═══════════════════════════════════════════════════════════════════════════════

@app.post("/api/redeem")
async def redeem_token(
    access_token: str = Form(...),
    upload_token: str = Form(...),
):
    """
    Validate an admin-issued access token against the current upload.
    Access token is free-standing (not tied to email) and reusable.
    Returns full changelog + a fresh single-use download token.
    """
    token_entry = issued_tokens.get(access_token.strip())
    if not token_entry:
        raise HTTPException(404, "Invalid or expired access token.")

    upload_entry = pending_uploads.get(upload_token)
    if not upload_entry:
        raise HTTPException(
            410,
            "Your file session has expired — please re-upload your file and try again.",
        )

    # Record usage
    token_entry["use_count"] += 1
    token_entry["last_used"]  = datetime.now(timezone.utc).isoformat()

    # Issue a fresh single-use download token
    dl_token = secrets.token_urlsafe(32)
    download_tokens[dl_token] = upload_entry

    return {
        "ok":             True,
        "download_token": dl_token,
        "changelog":      upload_entry["changelog"],   # full, unredacted
    }


# ═══════════════════════════════════════════════════════════════════════════════
# ROUTES — DOWNLOAD
# ═══════════════════════════════════════════════════════════════════════════════

@app.get("/api/download/{download_token}")
async def download(download_token: str):
    entry = download_tokens.pop(download_token, None)
    if not entry:
        raise HTTPException(404, "Download token not found or already used.")
    raw_bytes     = entry["raw"]
    framework_ids = entry["frameworks"]
    filename      = entry.get("filename", "collection.json")
    try:
        parsed = _parse_file(raw_bytes, filename)
    except Exception as exc:
        raise HTTPException(422, f"Could not parse file: {exc}") from exc
    fixed, changelog = transform(parsed, framework_ids)
    stem     = filename.rsplit(".", 1)[0]
    fw_sfx   = "_".join(f.lower() for f in framework_ids)
    out_name = f"{stem}_compliant_{fw_sfx}"
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(f"{out_name}.json",           json.dumps(fixed, indent=2, ensure_ascii=False))
        zf.writestr(f"{out_name}_changelog.json", json.dumps(changelog, indent=2, ensure_ascii=False))
        zf.writestr(f"{out_name}_summary.md",     _build_md(changelog))
    buf.seek(0)
    return StreamingResponse(
        buf, media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{out_name}.zip"'},
    )


# ═══════════════════════════════════════════════════════════════════════════════
# ROUTES — ADMIN
# ═══════════════════════════════════════════════════════════════════════════════

@app.get("/admin", response_class=HTMLResponse)
async def admin_dashboard(key: str = ""):
    """Minimal HTML admin page — list issued tokens + generate new ones."""
    _require_admin(key)

    rows = ""
    for tok, meta in issued_tokens.items():
        short = tok[:12] + "…"
        rows += f"""
        <tr>
          <td><code>{short}</code></td>
          <td>{meta.get('label','—')}</td>
          <td>{meta.get('email','—')}</td>
          <td>{meta.get('created_at','')[:10]}</td>
          <td>{meta.get('use_count', 0)}</td>
          <td>{meta.get('last_used','never')[:16]}</td>
          <td>
            <button onclick="copyToken('{tok}')" class="copy-btn">Copy full token</button>
          </td>
        </tr>"""

    if not rows:
        rows = '<tr><td colspan="7" style="text-align:center;color:#4a6480;padding:24px">No tokens issued yet.</td></tr>'

    return HTMLResponse(f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Admin — API Compliance Fixer</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: #070b10; color: #b0c4d8; font-family: 'Segoe UI', sans-serif;
         font-size: 14px; padding: 32px; }}
  h1 {{ color: #e2eef8; font-size: 20px; margin-bottom: 6px; }}
  .sub {{ color: #4a6480; font-size: 12px; margin-bottom: 32px; font-family: monospace; }}
  .card {{ background: #0d1420; border: 1px solid #1a2840; border-radius: 10px;
           padding: 24px; margin-bottom: 24px; }}
  h2 {{ color: #e2eef8; font-size: 14px; font-weight: 600; margin-bottom: 16px;
        font-family: monospace; letter-spacing: .06em; text-transform: uppercase; }}
  label {{ display: block; font-size: 11px; color: #4a6480; letter-spacing: .08em;
           text-transform: uppercase; margin-bottom: 6px; margin-top: 12px; }}
  input {{ background: #121c2c; border: 1px solid #223352; border-radius: 6px;
           padding: 9px 12px; color: #e2eef8; font-family: monospace; font-size: 13px;
           width: 100%; outline: none; }}
  input:focus {{ border-color: #00c8ff; }}
  .btn {{ background: #00c8ff; color: #070b10; border: none; border-radius: 7px;
          padding: 10px 20px; font-size: 13px; font-weight: 700; cursor: pointer;
          margin-top: 16px; font-family: monospace; }}
  .btn:hover {{ background: #33d6ff; }}
  .copy-btn {{ background: #1a2840; color: #b0c4d8; border: 1px solid #223352;
               border-radius: 5px; padding: 4px 10px; font-size: 11px; cursor: pointer;
               font-family: monospace; }}
  .copy-btn:hover {{ border-color: #00c8ff; color: #00c8ff; }}
  table {{ width: 100%; border-collapse: collapse; }}
  th {{ text-align: left; font-size: 10px; letter-spacing: .1em; text-transform: uppercase;
        color: #4a6480; padding: 0 12px 10px 0; border-bottom: 1px solid #1a2840; }}
  td {{ padding: 10px 12px 10px 0; border-bottom: 1px solid #111820; vertical-align: middle; }}
  code {{ font-family: monospace; color: #00c8ff; font-size: 12px; }}
  .result {{ background: #0d1c10; border: 1px solid #0d3d1a; border-radius: 8px;
             padding: 16px; margin-top: 16px; display: none; }}
  .result code {{ font-size: 14px; color: #00d490; word-break: break-all; }}
  .result .lbl {{ font-size: 10px; color: #4a6480; letter-spacing: .06em;
                  text-transform: uppercase; margin-bottom: 6px; }}
  .toast {{ position: fixed; bottom: 24px; right: 24px; background: #00d490; color: #070b10;
            padding: 10px 18px; border-radius: 8px; font-family: monospace; font-size: 13px;
            font-weight: 700; display: none; }}
</style>
</head>
<body>

<h1>⚡ API Compliance Fixer — Admin</h1>
<div class="sub">All tokens live in memory. They reset on redeploy.</div>

<!-- Generate token -->
<div class="card">
  <h2>Generate Access Token</h2>
  <label>Label (who is this for?)</label>
  <input type="text" id="g-label" placeholder="e.g. Mohammed Al-Rashid — Riyad Bank">
  <label>Email (optional — for your records)</label>
  <input type="text" id="g-email" placeholder="user@bank.sa">
  <br>
  <button class="btn" onclick="generateToken()">Generate Token</button>

  <div class="result" id="result">
    <div class="lbl">Access token — copy and send to user</div>
    <code id="result-token"></code>
  </div>
</div>

<!-- Token list -->
<div class="card">
  <h2>Issued Tokens ({len(issued_tokens)})</h2>
  <table>
    <thead>
      <tr>
        <th>Token</th>
        <th>Label</th>
        <th>Email</th>
        <th>Created</th>
        <th>Uses</th>
        <th>Last used</th>
        <th></th>
      </tr>
    </thead>
    <tbody>{rows}</tbody>
  </table>
</div>

<div class="toast" id="toast">Copied!</div>

<script>
const KEY = new URLSearchParams(location.search).get('key') || '';

async function generateToken() {{
  const label = document.getElementById('g-label').value.trim();
  const email = document.getElementById('g-email').value.trim();
  if (!label) {{ alert('Please enter a label.'); return; }}

  const params = new URLSearchParams({{ key: KEY, label, email }});
  const res  = await fetch('/admin/generate?' + params);
  const data = await res.json();

  if (!res.ok) {{ alert(data.detail || 'Error generating token.'); return; }}

  document.getElementById('result-token').textContent = data.access_token;
  document.getElementById('result').style.display = 'block';

  // Refresh page to update token list
  setTimeout(() => location.reload(), 1500);
}}

function copyToken(tok) {{
  navigator.clipboard.writeText(tok);
  const t = document.getElementById('toast');
  t.style.display = 'block';
  setTimeout(() => t.style.display = 'none', 1800);
}}
</script>
</body>
</html>""")


@app.get("/admin/generate")
async def generate_token(key: str = "", label: str = "", email: str = ""):
    """Generate a new free-standing access token. Returns JSON."""
    _require_admin(key)
    if not label:
        raise HTTPException(400, "Label is required (who is this token for?).")

    token = secrets.token_urlsafe(32)
    issued_tokens[token] = {
        "label":      label,
        "email":      email.strip().lower(),
        "created_at": datetime.now(timezone.utc).isoformat(),
        "use_count":  0,
        "last_used":  "never",
    }
    print(f"[ADMIN] Token generated for '{label}' ({email}): {token[:12]}…")
    return {
        "access_token": token,
        "label":        label,
        "email":        email,
        "created_at":   issued_tokens[token]["created_at"],
    }


@app.get("/admin/tokens")
async def list_tokens(key: str = ""):
    """List all issued tokens. Returns JSON."""
    _require_admin(key)
    return [
        {"token_prefix": tok[:12] + "…", **meta}
        for tok, meta in issued_tokens.items()
    ]


# ═══════════════════════════════════════════════════════════════════════════════
# MARKDOWN BUILDER
# ═══════════════════════════════════════════════════════════════════════════════

def _build_md(cl: dict) -> str:
    lines = [
        "# API Compliance Fix Summary", "",
        f"**Tool:** {cl.get('tool')} v{cl.get('version')}",
        f"**Generated:** {cl.get('generated_at')}",
        f"**Collection:** {cl.get('collection_name')}",
        f"**Frameworks:** {', '.join(cl.get('frameworks', []))}",
        f"**Total changes:** {cl.get('total_changes', 0)}", "",
        "## Severity Breakdown", "",
    ]
    sev = cl.get("severity_summary", {})
    for s in ("critical", "high", "medium", "info"):
        lines.append(f"- **{s.capitalize()}:** {sev.get(s, 0)}")
    lines += ["", "## Changes by Rule", ""]
    for rule in cl.get("changes_by_rule", []):
        lines.append(f"### [{rule['rule_id']}] {rule['rule_title']}")
        lines.append(f"*{rule.get('reference', '')}* · Severity: **{rule.get('severity', '')}**\n")
        for req in rule.get("affected_requests", []):
            lines.append(f"- `{req['request']}` — {req['detail']}")
        lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", "8000"))
    uvicorn.run("main:app", host="0.0.0.0", port=port, reload=True)
